#!/usr/bin/env bash
#
passwd_file="/etc/passwd"

if [ -e "$passwd_file" ]; then
    while IFS=: read -r username _ uid _ _ home _; do
        echo "Username: $username"
        echo "User ID: $uid"
        echo "Home Directory: $home"
        echo "-----------------------"
    done < "$passwd_file"
fi
