#!/usr/bin/env bash
# displays username user id and home directory in /etc/passwd
passwd_file="/etc/passwd"

if [ -e "$passwd_file" ]; then
    while IFS=: read -r username _ uid _ _ home _; do
        echo "Username: $username"
        echo "User ID: $uid"
        echo "Home Directory: $home"
    done < "$passwd_file"
else
    echo "Error: /etc/passwd file not found."
fi
