#!/usr/bin/env bash
# story of passwd
passwd_file="/etc/passwd"

if [ -e "$passwd_file" ]; then
    while IFS=: read -r username _ uid gid gecos home shell; do
        echo "The user $username is part of the $gid gang, lives in $home and rides $shell."
        echo "USER ID's place is protected by the passcode ********, more info about the user here: $gecos"
    done < "$passwd_file"
else
    echo "Error: /etc/passwd file not found."
fi
