#!/usr/bin/env bash
# bash script that displays Best School 10 times and Hi when it reaches 9
counter=1

while [ $counter -le 10 ]; do
	if [ $counter -eq 9 ]; then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	((counter++))
done
