#!/usr/bin/env bash
# bash script that displays numbers 1-20 and gives bad luck on 4,9,and 17
counter=1

while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo "$counter"
            echo "bad luck from China"
            ;;
        9)
            echo "$counter"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$counter"
            echo "bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac
    ((counter++))
done
