#!/usr/bin/env bash
# bash script that diplays the cwd in list format 
for file in *; do
    if [[ ! $file == .* ]]; then
        name_part=$(echo "$file" | cut -d'-' -f2-)
        echo "$name_part"
    fi
done
